### ISSUE TITLE
Access denied authentication failed

### ISSUE THREAD

**Issue by kevin321happy** [airwallex/airwallex-payment-ios#65]
通过AirwallexRecurringSession的方式 拉起支付报错：Access denied authentication failed，

<img width="782" alt="image" src="https://github.com/airwallex/airwallex-payment-ios/assets/24783813/334b3c7d-8b17-4ec4-b65a-d076ce5163bf">
<img width="445" alt="image" src="https://github.com/airwallex/airwallex-payment-ios/assets/24783813/a696277f-6076-493a-8224-406537d72b6c">
 请问这个是什么原因呢

**Comment by aw-hector** [comment]
> 通过AirwallexRecurringSession的方式 拉起支付报错：Access denied authentication failed，
> 
> <img alt="image" width="782" src="https://private-user-images.githubusercontent.com/24783813/340256050-334b3c7d-8b17-4ec4-b65a-d076ce5163bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODg2OTYsIm5iZiI6MTcyMjU4ODM5NiwicGF0aCI6Ii8yNDc4MzgxMy8zNDAyNTYwNTAtMzM0YjNjN2QtOGIxNy00ZWM0LWI2NWEtZDA3NmNlNTE2M2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOTFjN2U4MTFiMGUxOGUxZGY5YzY1YWUwMzk2MWJmYmQwNDljMzA4N2VlMWU1MjAzZGQ4NDZiYWQwNjFmNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sWQ-qXm3q5QNENYR3G9gAUUBfOUyMdw7X0NoljitHVY"> <img alt="image" width="445" src="https://private-user-images.githubusercontent.com/24783813/340256143-a696277f-6076-493a-8224-406537d72b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODg2OTYsIm5iZiI6MTcyMjU4ODM5NiwicGF0aCI6Ii8yNDc4MzgxMy8zNDAyNTYxNDMtYTY5NjI3N2YtNjA3Ni00OTNhLTgyMjQtNDA2NTM3ZDcyYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzJhOTMwM2JkYTBkMDg3ZTk4ZjE4NGNkMmQzMmFhZTI3NzNjYWJkYTE3Mjc0Yzk0MTllOGFjMjgxNjhhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ixa5PFdwigT2e1gPAf1VABfcX4YgLYsQWVybZxUIuK4"> 请问这个是什么原因呢

Have you configured client secret (fetched from your backend server) in AWXAPIClientConfiguration like in our sample code?
`[AWXAPIClientConfiguration sharedConfiguration].clientSecret = _customerSecret;`

**Comment by aw-hector** [comment]
Closed due to inactivities.

**Comment by aw-hector** [comment]
Closed due to inactivities.
